repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        types_or: [astro, css, scss, javascript, jsx, ts, tsx, svelte, json, markdown, yaml, html]
